import { Metadata } from "next";
import "../globals.css";

export const metadata: Metadata = {
  title: "Blogish Studio",
  description: "Generated by create next app and Sanity Studio CMS",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
