import type { Metadata } from "next";
import "../globals.css";
import Header from "@/components/Header";
import Banner from "@/components/Banner";

export const metadata: Metadata = {
  title: "Blogish",
  description: "Generated by create next app and Sanity Studio CMS",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <Banner />
        {children}
      </body>
    </html>
  );
}
